### ISSUE TITLE
On Mac there is no Shortcut available to leave image view and go back to page

### ISSUE THREAD

**Issue by hirschferkel** [sblask/webextension-image-forward#95]
On Mac there is no Shortcut available to leave image view and go back to the initial page.

Alt + Space will work the same way like Shift + Alt + Space

**Comment by sblask** [comment]
You can set your own on under chrome://extensions/shortcuts Option+Space and Option+Shift+Space are taken already:

<img width="674" alt="Screenshot 2023-04-19 at 21 32 40" src="https://user-images.githubusercontent.com/681955/233033233-e144d395-cb17-4ccb-8c09-06ad9b0143de.png">

**Comment by hirschferkel** [comment]
It does not work in Firefox so ...

**Comment by sblask** [comment]
https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox
